
Spatial Resolution: 3.0  # cm
Temporal Resolution: 1.0  # ms
Equilibration Duration: 250. # ms

Selectivity Type Probabilities:
  PYR:
    constant: 1.0
  PVBC:
    constant: 1.0
  OLM:
    constant: 1.0
  AAC:
    constant: 1.0
  BS:
    constant: 1.0
  CCKBC:
    constant: 1.0
  IVY:
    constant: 1.0
  NGFC:
    constant: 1.0
  SCA:
    constant: 1.0
  IS1:
    constant: 1.0
  IS2:
    constant: 1.0
  IS3:
    constant: 1.0
  CA3:
    constant: 1.0
  CA2:
    constant: 1.0
  EC:
    constant: 1.0

## Data from Pelkey KA, Chittajallu R, Craig MT, Tricoire L, Wester JC, McBain CJ. Hippocampal GABAergic Inhibitory Interneurons. Physiol Rev. 2017 Oct 1;97(4):1619-1747.

Peak Rate:
  PYR:
    constant: 2.0
  AAC:
    constant: 10.0
  PVBC:
    constant: 21.0
  BS:
    constant: 18.0
  OLM:
    constant: 10.0
  CCKBC:
    constant: 24.0
  IVY:
    constant: 3.0
  NGFC:
    constant: 10.0
  SCA:
    constant: 5.0
  IS1:
    constant: 20.0
  IS2:
    constant: 20.0
  IS3:
    constant: 20.0
  CA3:
    constant: 5.0
  CA2:
    constant: 5.0
  EC:
    constant: 2.0
    


Global Oscillation:
  frequency: 5.0 # oscillation frequency
  Phase Distribution:  # parameters of phase distribution along septotemporal axis
    slope: 16.5
    offset: 0.0
  Phase Modulation: # cell type-specific modulation
    PYR:
      phase range: [0, 150]
      depth: 0.5
    PVBC:
      phase range: [180, 540]
      depth: 0.8
    OLM:
      phase range: [200, 560]
      depth: 0.8

Arena:
  A:
    Domain:
      vertices: [[-100, -100], [-100, 100], [100, 100], [100, -100]]
      simplices: [[0,1], [1,2], [2,3], [3,0]]

    Trajectory:
      Diag:
        path: [[-100, -100], [100, 100]]
        run velocity: 30.  # cm/s


    default run velocity: 30.  # cm/s

  Calibration:
    Domain:
      vertices: [[-32.5, -32.5], [-32.5, 32.5], [32.5, 32.5], [32.5, -32.5]]
      simplices: [[0,1], [1,2], [2,3], [3,0]]

# Opsin:
#   nstates: 6
#   opsin type: "ChR2"
#   rho parameters:
#     expProb: 1.0
#   protocol: step
#   protocol parameters:
#     Dt_delay: 150
#     phis: [1e15, 1e15]
#     cycles: [[ 10,  150], [ 10,  150], [ 10,  150], [ 10,  150], [ 10,  150], [ 10,  150],  [ 10,  150],  [ 10,  150],  [  10, 100]]
