## Schafer Collateral Associated synapse density configuration

## https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6782984/
## Calretinin


basal:
  excitatory:
    SO:
      mean: 2.0
      variance: 0.1

  inhibitory:
    SO:
      mean: 0.5
      variance: 0.1
      
apical:
  excitatory:
    SLM:
      mean: 4.0
      variance: 0.1
    SR:
      mean: 2.0
      variance: 0.1

  inhibitory:
    SLM:
      mean: 1.0
      variance: 0.1
    SR:
      mean: 0.5
      variance: 0.1
soma:
  inhibitory:
    default:
      mean: 0.2
      variance: 0.1
  excitatory:
    default:
      mean: 0.4
      variance: 0.1
