     Synapse Mechanisms:
  AMPA: LinExp2Syn
  NMDA: LinExp2SynNMDA
  GABA_A: LinExp2Syn
  GABA_B: LinExp2Syn
Synapse Parameter Rules: !include Synapse_Parameter_Rules.yaml
Axon Extent: !include Axon_Extent.yaml
Connection Velocity: !include Connection_Velocity.yaml
Synapses:
  PYR:
    STIM:
      type: excitatory
      sections: [soma, basal, apical]
      layers: [SO, SO, SO]
      proportions: [0.1, 0.1, 0.1]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 0.00001
          weight: 0.0
        NMDA:
          g_unit: 0.00001
          weight: 0.0
    PYR:
      type: excitatory
      sections: [soma, basal, apical]
      layers: [SO, SO, SO]
      proportions: [0.9, 0.9, 0.9]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 0.00001
          weight: 0.5
        NMDA:
          g_unit: 0.00001
          weight: 0.5
    PVBC:
      type: inhibitory
      sections: [soma, basal, apical, ais]
      layers: [SO, SO, SO, SO]
      proportions: [0.5, 0.5, 0.5, 1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.30
          tau_decay: 6.2
          e: -60
          g_unit: 0.005
          weight: 0.005
    OLM:
      type: inhibitory
      sections: [soma, basal, apical]
      layers: [SO, SO, SO]
      proportions: [0.5, 0.5, 0.5]
      mechanisms:
        GABA_A:
          tau_rise: 0.50
          tau_decay: 9.0
          e: -60
          g_unit: 0.0033
          weight: 0.005
  PVBC:
    PYR:
      type: excitatory
      sections: [soma, apical, basal]
      layers: [SO, SO, SO]
      proportions: [0.5, 0.5, 0.5]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 0.0005
          weight: 0.005
    STIM:
      type: excitatory
      sections: [soma, apical, basal]
      layers: [SO, SO, SO]
      proportions: [0.5, 0.5, 0.5]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 0.0002
          weight: 0
    PVBC:
      type: inhibitory
      sections: [soma, apical, basal]
      layers: [SO, SO, SO]
      proportions: [1.0, 0.5, 1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.08
          tau_decay: 4.8
          e: -60
          g_unit: 0.001
          weight: 0.0
    OLM:
      type: inhibitory
      sections: [apical]
      layers: [SO]
      proportions: [0.5]
      mechanisms:
        GABA_A:
          tau_rise: 0.08
          tau_decay: 4.8
          e: -60
          g_unit: 0.001
          weight: 0.0
  OLM:
    PYR:
      type: excitatory
      sections: [apical, basal]
      layers: [SO, SO]
      proportions: [1.0, 1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 0.001
          weight: 0.01
    PVBC:
      type: inhibitory
      sections: [basal, soma, apical]
      layers: [SO, SO, SO]
      proportions: [1.0, 1.0, 1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.08
          tau_decay: 4.8
          e: -60
          g_unit: 0.0001
          weight: 0.0
