Synaptic Optimization:
  PYR:
    Parameter ranges:
      Weight all:
        CA2:
          basal:
            AMPA:
              weight: [0.1, 10.0]
        CA3:
          !!python/tuple [apical, basal]:
            AMPA:
              weight: [0.1, 10.0]
        PYR:
          !!python/tuple [soma, basal]:
            AMPA:
              weight: [0.1, 10.0]
        EC:
          !!python/tuple [apical, basal]:
            AMPA:
              weight: [0.1, 10.0]
        AAC:
          ais:
            GABA_A:
              weight: [0.1, 10.0] 
        PVBC:
          !!python/tuple [apical, basal, soma]:
            GABA_A:
              weight: [0.1, 10.0]
        CCKBC:
          !!python/tuple [apical, basal, soma]:
            GABA_A:
              weight: [0.1, 10.0]
        BS:
          !!python/tuple [apical, basal]:
            GABA_A:
              weight: [0.1, 10.0]
        IVY:
          !!python/tuple [apical, basal]:
            GABA_A:
              weight: [0.1, 10.0]
        SCA:
          !!python/tuple [apical, basal]:
            GABA_A:
              weight: [0.1, 10.0]
        NGFC:
          apical:
            GABA_A:
              weight: [0.1, 10.0]
            GABA_B:
              weight: [0.1, 10.0]
        OLM:
          !!python/tuple [apical, basal]:
            GABA_A:
              weight: [0.1, 10.0]
    Targets:
      state:
        v:
          baseline: -65.0
          threshold: -30.0
          margin: 4.0
      firing rate: 2.0
      fraction active: 0.33
  CCKBC:
    Targets:
      state:
        v:
          threshold: -43.1
          margin: 2.0
      firing rate: 9.0 # CCK+ data from Klausberger et al. J Neurosci 2005 
      fraction active: 0.9
    Parameter ranges:
      Weight all:
        EC:
          apical:
            AMPA:
              weight: [0.1, 10.0]
        CA2:
          !!python/tuple [apical, basal]:
            AMPA:
              weight: [0.1, 10.0]
        CA3:
          !!python/tuple [apical, basal, soma]:
            AMPA:
              weight: [0.1, 10.0]
        PYR:
          basal:
            AMPA:
              weight: [0.1, 10.0]
        PVBC:
          !!python/tuple [soma, basal]:
            GABA_A:
              weight: [0.1, 2.0]
        CCKBC:
          !!python/tuple [soma, apical, basal]:
            GABA_A:
              weight: [0.1, 2.0]
        BS:
          apical:
            GABA_A:
              weight: [0.1, 2.0]
        IVY:
          apical:
            GABA_A:
              weight: [0.1, 2.0]
        SCA:
          apical:
            GABA_A:
              weight: [0.1, 2.0]
        NGFC:
          apical:
            GABA_A:
              weight: [0.1, 2.0]
            GABA_B:
              weight: [0.1, 2.0]
        OLM:
          apical:
            GABA_A:
              weight: [0.1, 2.0]
        IS1:
          !!python/tuple [apical, basal]:
            GABA_A:
              weight: [0.1, 2.0]
        IS2:
          apical:
            GABA_A:
              weight: [0.1, 2.0]
        IS3:
          basal:
            GABA_A:
              weight: [0.1, 2.0]
  BS:
    Targets:
      state:
        v:
          threshold: -43.1
          margin: 2.0
      firing rate: 18.0 # mean PV+ FR in Allen Neuropixels data
      fraction active: 0.9
    Parameter ranges:
      Weight all:
        EC:
          apical:
            AMPA:
              weight: [0.1, 20.0]
        CA2:
          !!python/tuple [apical, basal]:
            AMPA:
              weight: [0.1, 20.0]
        CA3:
          !!python/tuple [apical, basal]:
            AMPA:
              weight: [0.1, 20.0]
        PYR:
          !!python/tuple [soma, basal]:
            AMPA:
              weight: [0.1, 20.0]
        PVBC:
          !!python/tuple [soma, basal]:
            GABA_A:
              weight: [0.1, 20.0]
        CCKBC:
          !!python/tuple [soma, apical]:
            GABA_A:
              weight: [0.1, 20.0]
        BS:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
        IVY:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
        SCA:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
        OLM:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
        NGFC:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
            GABA_B:
              weight: [0.1, 20.0]
        IS1:
          basal:
            GABA_A:
              weight: [0.1, 20.0]
        IS3:
          basal:
            GABA_A:
              weight: [0.1, 20.0]
            
  AAC:
    Targets:
      state:
        v:
          threshold: -43.1
          margin: 2.0
      firing rate: 18.0 # mean PV+ FR in Allen Neuropixels data
      fraction active: 0.9
    Parameter ranges:
      Weight all:
        CA2:
          !!python/tuple [apical, basal]:
            AMPA:
              weight: [0.1, 20.0]
            NMDA:
              weight: [0.1, 20.0]
        CA3:
          !!python/tuple [apical, basal]:
            AMPA:
              weight: [0.1, 20.0]
            NMDA:
              weight: [0.1, 20.0]
        EC:
          apical:
            AMPA:
              weight: [0.1, 20.0]
            NMDA:
              weight: [0.1, 20.0]
        PYR:
          !!python/tuple [basal, soma]:
            AMPA:
              weight: [0.1, 20.0]
            NMDA:
              weight: [0.1, 20.0]
        PVBC:
          !!python/tuple [apical, basal, soma]:
            GABA_A:
              weight: [0.1, 20.0]
        CCKBC:
          !!python/tuple [apical, soma]:
            GABA_A:
              weight: [0.1, 20.0]
        BS:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
        IVY:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
        SCA:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
        NGFC:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
            GABA_B:
              weight: [0.1, 20.0]
        OLM:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
  PVBC:
    Targets:
      state:
        v:
          threshold: -43.1
          margin: 2.0
      firing rate: 18.0 # mean PV+ FR in Allen Neuropixels data
      fraction active: 0.9
    Parameter ranges:
      Weight all:
        CA2:
          !!python/tuple [apical, basal]:
            AMPA:
              weight: [0.1, 20.0]
            NMDA:
              weight: [0.1, 20.0]
        CA3:
          !!python/tuple [apical, basal]:
            AMPA:
              weight: [0.1, 20.0]
            NMDA:
              weight: [0.1, 20.0]
        EC:
          apical:
            AMPA:
              weight: [0.1, 20.0]
            NMDA:
              weight: [0.1, 20.0]
        PYR:
          !!python/tuple [basal, soma]:
            AMPA:
              weight: [0.1, 20.0]
            NMDA:
              weight: [0.1, 20.0]
        PVBC:
          !!python/tuple [apical, basal, soma]:
            GABA_A:
              weight: [0.1, 20.0]
        CCKBC:
          !!python/tuple [apical, soma]:
            GABA_A:
              weight: [0.1, 20.0]
        BS:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
        IVY:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
        SCA:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
        NGFC:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
            GABA_B:
              weight: [0.1, 20.0]
        OLM:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
  IS1:
    Targets:
      state:
        v:
          threshold: -43.1
          margin: 2.0
      firing rate: 17.0 # mean VIP+ FR in Allen Neuropixels data
      fraction active: 0.9
    Parameter ranges:
      Weight all:
        CA2:
          !!python/tuple [apical, basal]:
            AMPA:
              weight: [0.1, 20.0]
        CA3:
          !!python/tuple [apical, basal]:
            AMPA:
              weight: [0.1, 20.0]
        PYR:
          !!python/tuple [soma, basal]:
            AMPA:
              weight: [0.1, 20.0]
            NMDA:
              weight: [0.1, 20.0]
        PVBC:   
          soma:
            GABA_A:
              weight: [0.1, 20.0]
        BS:   
          apical:
            GABA_A:
              weight: [0.1, 20.0]
        IVY:
          !!python/tuple [apical, basal]:
            GABA_A:
              weight: [0.1, 20.0]
        SCA:
          !!python/tuple [apical, basal]:
            GABA_A:
              weight: [0.1, 20.0]
        IS1: 
          basal:
            GABA_A:
              weight: [0.1, 20.0]
        IS2: 
          apical:
            GABA_A:
              weight: [0.1, 20.0]
  IS2:
    Targets:
      state:
        v:
          threshold: -43.1
          margin: 2.0
      firing rate: 17.0 # mean VIP+ FR in Allen Neuropixels data
      fraction active: 0.9
    Parameter ranges:
      Weight all:
        EC:
          apical:
            AMPA:
              weight: [0.1, 10.0]
        CA3:
          !!python/tuple [soma, apical, basal]:
            AMPA:
              weight: [0.1, 10.0]
        NGFC: 
          !!python/tuple [soma, apical, basal]:
            GABA_A:
              weight: [0.1, 10.0]
        SCA: 
          basal:
            GABA_A:
              weight: [0.1, 10.0]
        IS1: 
          !!python/tuple [soma, apical]:
            GABA_A:
              weight: [0.1, 10.0]
        
  IS3:
    Targets:
      state:
        v:
          threshold: -43.1
          margin: 2.0
      firing rate: 17.0 # mean VIP+ FR in Allen Neuropixels data
      fraction active: 0.9
    Parameter ranges:
      Weight all:
        CA2:
          !!python/tuple [soma, apical, basal]:
            AMPA:
              weight: [0.1, 10.0]
        CA3:
          !!python/tuple [soma, apical, basal]:
            AMPA:
              weight: [0.1, 10.0]
        EC:
          apical:
            AMPA:
              weight: [0.1, 10.0]
        PYR:
          basal:
            AMPA:
              weight: [0.1, 10.0]
        PVBC:
          soma:
            GABA_A:
              weight: [0.1, 10.0]
        BS:
          !!python/tuple [apical, basal]:
            GABA_A:
              weight: [0.1, 10.0]
        IVY:
          !!python/tuple [apical, basal]:
            GABA_A:
              weight: [0.1, 10.0]
        SCA:
          apical:
            GABA_A:
              weight: [0.1, 10.0]
        NGFC:
          apical:
            GABA_A:
              weight: [0.1, 10.0]
        IS1:
          apical:
            GABA_A:
              weight: [0.1, 10.0]
        IS2:
          apical:
            GABA_A:
              weight: [0.1, 10.0]
  OLM:
    Targets:
      state:
        v:
          threshold: -43.1
          margin: 2.0
      firing rate: 13.0 # mean SST+ FR in Allen Neuropixels data
      fraction active: 0.9
    Parameter ranges:
      Weight all:
        PYR:
          !!python/tuple [soma, basal]:
            AMPA:
              weight: [0.1, 20.0]
        OLM:
          basal:
            GABA_A:
              weight: [0.1, 20.0]
        IS3:
          basal:
            GABA_A:
              weight: [0.1, 20.0]
  IVY:
    Targets:
      state:
        v:
          threshold: -43.1
          margin: 2.0
      firing rate: 3.0 # Table 6 in Bezaire et al. 2016
      fraction active: 0.9
    Parameter ranges:
      Weight all:
        CA2:
          !!python/tuple [apical, basal]:
            AMPA:
              weight: [0.1, 20.0]
            NMDA:
              weight: [0.1, 20.0]
        CA3:
          !!python/tuple [soma, apical, basal]:
            AMPA:
              weight: [0.1, 20.0]
            NMDA:
              weight: [0.1, 20.0]
        PYR:
          !!python/tuple [apical, basal]:
            AMPA:
              weight: [0.1, 20.0]
            NMDA:
              weight: [0.1, 20.0]
        PVBC:
          soma:
            GABA_A:
              weight: [0.1, 20.0]
        CCKBC:
          !!python/tuple [soma, apical, basal]:
            GABA_A:
              weight: [0.1, 20.0]
        BS:
          !!python/tuple [apical, basal]:
            GABA_A:
              weight: [0.1, 20.0]
        IVY:
          !!python/tuple [apical, basal]:
            GABA_A:
              weight: [0.1, 20.0]
        SCA:
          !!python/tuple [apical, basal]:
            GABA_A:
              weight: [0.1, 20.0]
        NGFC:
          !!python/tuple [apical, basal]:
            GABA_A:
              weight: [0.1, 20.0]
            GABA_B:
              weight: [0.1, 20.0]
        IS1:
          !!python/tuple [apical, basal]:
            GABA_A:
              weight: [0.1, 20.0]
        IS2:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
  NGFC:
    Targets:
      state:
        v:
          threshold: -43.1
          margin: 2.0
      firing rate: 7.4 # Sakalar et al. Science 2022
      fraction active: 0.9
    Parameter ranges:
      Weight all:
        EC:
          !!python/tuple [apical, basal]:
            AMPA:
              weight: [0.1, 20.0]
            NMDA:
              weight: [0.1, 20.0]
        CA3:
          basal:
            AMPA:
              weight: [0.1, 20.0]
            NMDA:
              weight: [0.1, 20.0]
        BS:
          basal:
            GABA_A:
              weight: [0.1, 20.0]
        IVY:
          basal:
            GABA_A:
              weight: [0.1, 20.0]
        SCA:
          basal:
            GABA_A:
              weight: [0.1, 20.0]
        NGFC:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
            GABA_B:
              weight: [0.1, 20.0]
        OLM:
          apical:
            GABA_A:
              weight: [0.1, 20.0]
  SCA:
    Targets:
      state:
        v:
          threshold: -43.1
          margin: 2.0
      firing rate: 9.0 # CCK+ data from Klausberger et al. J Neurosci 2005 
      fraction active: 0.9
    Parameter ranges:
      Weight all:
        CA2:
          !!python/tuple [apical, basal]:
            AMPA:
              weight: [0.1, 10.0]
        CA3:
          !!python/tuple [apical, basal, soma]:
            AMPA:
              weight: [0.1, 10.0]
        EC:
          !!python/tuple [apical, basal, soma]:
            AMPA:
              weight: [0.1, 10.0]
        PYR:
          basal:
            AMPA:
              weight: [0.1, 10.0]
        PVBC:
          !!python/tuple [basal, soma]:
            GABA_A:
              weight: [0.1, 10.0]
        CCKBC:
          !!python/tuple [soma, basal]:
            GABA_A:
              weight: [0.1, 10.0]
        BS:
          apical:
            GABA_A:
              weight: [0.1, 10.0]
        IVY:
          apical:
            GABA_A:
              weight: [0.1, 10.0]
        SCA:
          apical:
            GABA_A:
              weight: [0.1, 10.0]
        NGFC:
          apical:
            GABA_A:
              weight: [0.1, 10.0]
            GABA_B:
              weight: [0.1, 10.0]
        OLM:
          apical:
            GABA_A:
              weight: [0.1, 10.0]
        IS1:
          !!python/tuple [basal, apical]:
            GABA_A:
              weight: [0.1, 10.0]
        IS2:
          apical:
            GABA_A:
              weight: [0.1, 10.0]
        
